## Library
Using numpy to provide the wanted values

In [94]:
import numpy as np

## Task 2a
Defining the matrix. First output is eigenvalues, and the second output is eigenvectors.

In [95]:
A = [[2,-1,0],[-1,2,-1],[0,-1,2]]
eigenvalues_A, eigenvectors_A = np.linalg.eig(A)

print('Eigenvalues:\n', eigenvalues_A)
print('Eigenvectors:\n', eigenvectors_A)

Eigenvalues:
 [3.41421356 2.         0.58578644]
Eigenvectors:
 [[-5.00000000e-01 -7.07106781e-01  5.00000000e-01]
 [ 7.07106781e-01  4.05405432e-16  7.07106781e-01]
 [-5.00000000e-01  7.07106781e-01  5.00000000e-01]]


## Task 2b
Defining the second matrix

In [103]:
B = [[1,2,3],[3,2,1],[1,0,-1]]
eigenvalues_B, eigenvectors_B = np.linalg.eig(B)

print('Eigenvalues:\n', eigenvalues_B)
print('Eigenvectors:\n', eigenvectors_B)

Eigenvalues:
 [ 4.31662479e+00 -2.31662479e+00  1.93041509e-17]
Eigenvectors:
 [[ 0.58428153  0.73595785  0.40824829]
 [ 0.80407569 -0.38198836 -0.81649658]
 [ 0.10989708 -0.55897311  0.40824829]]


#### Verification of values

In [104]:
lambda_1 = eigenvalues_B[0]
lambda_2 = eigenvalues_B[1]
lambda_3 = eigenvalues_B[2]
vector_1 = eigenvectors_B[:, 0]
vector_2 = eigenvectors_B[:, 1]
vector_3 = eigenvectors_B[:, 2]

# Checking eigenvectors
if np.allclose(np.dot(B, vector_1), lambda_1 * vector_1):
    print('Vector 1 correct')
if np.allclose(np.dot(B, vector_2), lambda_2 * vector_2):
    print('Vector 2 correct')
if np.allclose(np.dot(B, vector_3), lambda_3 * vector_3):
    print('Vector 3 correct')


Vector 1 correct
Vector 2 correct
Vector 3 correct
